import type { ProjectSpec } from '@vudt/spec'

/**
 * Renders `src/data/store.ts`: an in-memory store factory. Each page calls
 * `useCollectionRows` once and holds its own store — refresh or navigation
 * re-instantiates, so data resets (no backend, no persistence, no timers).
 */
export function renderStore(_spec: ProjectSpec): string {
  return [
    '// In-memory store factory. Pages instantiate their own store per route;',
    '// refresh or navigation resets the data (no backend, no persistence).',
    "import { MOCK_ROWS, type Row } from './mock'",
    '',
    'export interface CollectionStore {',
    '  rows: Row[]',
    '  search(query: string): Row[]',
    "  sort(field: string, dir: 'asc' | 'desc'): Row[]",
    '  page(pageSize: number, pageNum: number): Row[]',
    '  getById(id: string): Row | undefined',
    '  add(row: Row): void',
    '  /** Upsert: replace by id, or append with a generated id when absent. */',
    '  update(row: Record<string, unknown> & { id?: string }): void',
    '  remove(id: string): void',
    '}',
    '',
    'export function createCollectionStore(initial: Row[]): CollectionStore {',
    '  const rows = [...initial]',
    '  return {',
    '    rows,',
    '    search(query: string): Row[] {',
    "      const term = query.trim().toLowerCase()",
    "      if (term === '') return rows",
    '      return rows.filter((row) => JSON.stringify(row).toLowerCase().includes(term))',
    '    },',
    "    sort(field: string, dir: 'asc' | 'desc'): Row[] {",
    '      const factor = dir === \'asc\' ? 1 : -1',
    "      return [...rows].sort((a, b) => String(a[field] ?? '').localeCompare(String(b[field] ?? '')) * factor)",
    '    },',
    '    page(pageSize: number, pageNum: number): Row[] {',
    '      const start = (pageNum - 1) * pageSize',
    '      return rows.slice(start, start + pageSize)',
    '    },',
    '    getById(id: string): Row | undefined {',
    '      return rows.find((row) => row.id === id)',
    '    },',
    '    add(row: Row): void {',
    '      rows.push(row)',
    '    },',
    '    update(row: Record<string, unknown> & { id?: string }): void {',
    '      const index = rows.findIndex((existing) => existing.id === row.id)',
    '      if (index >= 0) rows[index] = row as Row',
    '      else rows.push({ ...row, id: `row-${rows.length + 1}` } as Row)',
    '    },',
    '    remove(id: string): void {',
    '      const index = rows.findIndex((row) => row.id === id)',
    '      if (index >= 0) rows.splice(index, 1)',
    '    },',
    '  }',
    '}',
    '',
    'export function useCollectionRows(id: string): CollectionStore {',
    '  return createCollectionStore(MOCK_ROWS[id] ?? [])',
    '}',
    '',
    'export function rowsToCsv(rows: readonly Row[]): string {',
    "  if (rows.length === 0) return ''",
    '  const headers = Object.keys(rows[0]!)',
    "  const lines = [headers.join(',')]",
    '  for (const row of rows) {',
    "    lines.push(headers.map((header) => String(row[header] ?? '')).join(','))",
    '  }',
    "  return lines.join('\\n')",
    '}',
    '',
    'export function downloadCsv(name: string, rows: readonly Row[]): void {',
    "  const blob = new Blob([rowsToCsv(rows)], { type: 'text/csv;charset=utf-8' })",
    '  const url = URL.createObjectURL(blob)',
    '  const anchor = document.createElement(\'a\')',
    '  anchor.href = url',
    '  anchor.download = `${name}.csv`',
    '  anchor.click()',
    '  URL.revokeObjectURL(url)',
    '}',
    '',
  ].join('\n')
}
